### ISSUE TITLE
add support for ubuntu 14

### ISSUE THREAD

**Issue by prune998** [alvaroaleman/ansible-gitea#2]
because it is hardcoded : 
```
gitea_supported_distributions:
  - CentOS-7
  - Ubuntu-16
  - Fedora-23
  - Fedora-24
```

change it to : 
```
gitea_supported_distributions:
  - CentOS-7
  - Ubuntu-16
  - Ubuntu-14
  - Fedora-23
  - Fedora-24
```

**Comment by alvaroaleman** [comment]
@prune998 Thanks for the hint. I don't use Ubuntu myself, do you mind creating a PR for that?

**Comment by prune998** [comment]
I've created pull requests, but wasn't able to clone to do it at once... this have not been tested yet, will try tomorrow...
